In [1]:
import distances
import numpy as np

In [2]:
x = np.array([[2, 3], [-1, 6], [10, 22]])
y = np.array([[1, 1], [-1, 2]])
distances.manhattan_distance(x, y)

In [3]:
np.sum(np.abs((x[:, None] - y)), axis=2)

In [4]:
x

In [5]:
y

In [6]:
import sklearn.neighbors

In [7]:
dist = sklearn.neighbors.DistanceMetric.get_metric('manhattan')

In [8]:
dist.pairwise(x, y)

array([[ 3.,  4.],
       [ 7.,  4.],
       [30., 31.]])

In [9]:
distances.chebyshev_distance(x, y)

array([[ 2,  3],
       [ 5,  4],
       [21, 20]])

In [10]:
dist = sklearn.neighbors.DistanceMetric.get_metric('chebyshev')

In [11]:
dist.pairwise(x, y)

array([[ 2.,  3.],
       [ 5.,  4.],
       [21., 20.]])

In [29]:
distances.minkowski_distance(x, y, p=100)

array([[1.        ,        nan],
       [       nan, 0.        ],
       [1.54498612,        nan]])

In [16]:
dist = sklearn.neighbors.DistanceMetric.get_metric('minkowski')
dist.pairwise(x, y)

array([[ 2.23606798,  3.16227766],
       [ 5.38516481,  4.        ],
       [22.84731932, 22.82542442]])